### ISSUE TITLE
LineLengthCheck: multiline strings should be ignored

### ISSUE THREAD

**Issue by Gama11** [adireddy/haxe-checkstyle#108]
``` haxe
    public static inline var TEST1:String = "
    class Test {
        var _a:Int;
        public function new() {
            _a = 10;
            if (_a > 200 && _a < 250 && _a != 240 && _a != 250 && _a != 260 && _a != 270 && _a != 280 && _a != 290 && _a > 200 && _a < 250 && _a != 240 && _a != 250 && _a != 260 && _a != 270 && _a != 280 && _a != 290) {
                _a = -1;
            }
        }
    }";
```

```
test/checks/size/LineLengthCheckTest.hx:33: characters 0-210 : Error: Too long line (> 160)
```

**Comment by adireddy** [comment]
I don't think we should ignore even if it's part of multiline string. The main purpose of line length check is to make the line readable without horizontal scrolling.

**Comment by Gama11** [comment]
There isn't really a good way to avoid it in multiline strings though (adding a line break changes the content).

**Comment by adireddy** [comment]
Ok then I willl keep this open and look into adding ignore pattern.

**Comment by Gama11** [comment]
This should be solvable the same way for all line based checks via some `isInMultilineString(pos)` function?

**Comment by adireddy** [comment]
but don't want to ignore all multiline strings if developers prefer splitting strings into multiple lines using `+`
