### ISSUE TITLE
OperatorWrap fails with generic types

### ISSUE THREAD

**Issue by fantoine** [adireddy/haxe-checkstyle#110]
With the following option:

``` json
        {
            "type": "OperatorWrap",
            "props": {
                "severity": "WARNING",
                "option": "nl"
            }
        }
```

I get this kind of errors:

```
Warning: LINE - 35: OperatorWrap - Token ">" must on a new line
```

When I have a method which defines a generic type as a return type, like this:

``` haxe
public static macro function build() : Array<Field>
```

**Comment by Gama11** [comment]
That example isn't quite enough to repro, here's a complete one:

``` haxe
class Test {
    function foo():Array<Int>
    {
        trace("test");
    }
}
```

**Comment by fantoine** [comment]
Sorry :)

**Comment by fantoine** [comment]
I also saw a typo on the error message. It should be

> Warning: LINE - 35: OperatorWrap - Token ">" must **be** on a new line

**Comment by Gama11** [comment]
No worries. :)

That one should be fixed on dev already: https://github.com/adireddy/haxe-checkstyle/blob/6b4cc47177cae789c84daf479df7f5188cb12184/src/checkstyle/checks/whitespace/WrapCheckBase.hx#L50
