### ISSUE TITLE
refactor ReturnCheck

### ISSUE THREAD

**Issue by AlexHaxe** [adireddy/haxe-checkstyle#18]
ReturnCheck is currently using string search to determine if a return occurs inside a field and this should be refactored.
e.g. anonymous functions inside a field body that return a value, even though the field itself returns Void (see CyclomaticComplexityChecks for false positives)

**Comment by adireddy** [comment]
Refactored ReturnCheck in `dev` branch.

**Comment by AlexHaxe** [comment]
I have not run a lot of checks, but I think just iterating over EBlock is not enough to catch all cases where a `return x;` could occur. I think we need to run a recursive loop over a number of ExprDef cases, at least for EBlock, EIf, ESwitch, EFor, ETry and EWhile. Because all of those can have an EReturn that effects the field.

**Comment by AlexHaxe** [comment]
I think we should also check for EFunction instances and run a check on them, because they can return something without specifying a return type as well, and that should be a checkstyle error.

**Comment by adireddy** [comment]
Yes more checks needed to cover all the cases. Are you happy to work on this whenever you get a chance? If yes please assign it to yourself so that we don't duplicate the effort.

**Comment by AlexHaxe** [comment]
Just merge a new version of ReturnCheck. I hope it covers all possible cases.

**Comment by adireddy** [comment]
that was quick :+1:
