### ISSUE TITLE
travisCI build fails on dev

### ISSUE THREAD

**Issue by AlexHaxe** [adireddy/haxe-checkstyle#20]
could not reproduce locally

**Comment by adireddy** [comment]
Looks like the issue is when using haxe 3.1.3

Temporarily changed travis to use 3.2.0 and it's fine. We should look into this.

**Comment by AlexHaxe** [comment]
fixed! Haxe 3.1.3 does not like `switch(null)`

**Comment by adireddy** [comment]
:+1:
