### ISSUE TITLE
How to use haxe-checkstyle in Intellij ?

### ISSUE THREAD

**Issue by dmouton** [adireddy/haxe-checkstyle#206]
Hi,
All is in the title ;)

**Comment by adireddy** [comment]
Depends on how you build.

If you are using `.hxml` to build you can add a step in that

```
-cmd haxelib run checkstyle -s src -c checkstyle.json -p report.xml -report
--next
```

The above is for the current v2 haxelib release.

**Comment by dmouton** [comment]
I thought of something more integrated as others linters like PHP Code Sniffer, or JSLint

**Comment by adireddy** [comment]
Well not as a plugin in intellij but I am trying to achieve similar functionality by integrating with https://codeclimate.com which is almost ready.

**Comment by adireddy** [comment]
I am working closely with codeclimate and currently testing the integration. Once ready you can simply add .codeclimate.yml to your project to use haxe-checksyle.
