### ISSUE TITLE
Check to detect unused local vars

### ISSUE THREAD

**Issue by Gama11** [adireddy/haxe-checkstyle#231]
Not much to be done about class fields, since a child class might depend on them, but those two should be doable.

Somewhat similar to `HiddenFieldCheck` I guess.

**Comment by AlexHaxe** [comment]
detecting unused function parameters might prove tricky

``` haxe
class Base {
  function doSomething(a:Int):Int {
    return 0;
  }
}

class Child {
  override function doSomething(a:Int):Int {
    return a;
  }
}
```

**Comment by adireddy** [comment]
Closing this. Reopen if there is any way to make this check happen.

**Comment by Gama11** [comment]
Should still be possible for local variables.
