### ISSUE TITLE
Check to detect missing new line at end of file

### ISSUE THREAD

**Issue by fantoine** [adireddy/haxe-checkstyle#240]
It's _generally_ a good practice to enforce a newline character at end of files.

Maybe it could deserve a check for this?

**Comment by adireddy** [comment]
Could be part of `EmptyLinesCheck` and the property can be `requireEmptyLineAtEOF`

**Comment by AlexHaxe** [comment]
How about three different modes
- last line is empty and has a NL (== double NL) 
- last line is not empty and has a NL (== insert_final_newline = true)
- last line is not empty and has no NL (== insert_final_newline = false)

**Comment by adireddy** [comment]
sounds good to me
