### ISSUE TITLE
More flexibility for InnerAssignment

### ISSUE THREAD

**Issue by fantoine** [adireddy/haxe-checkstyle#259]
Maybe InnerAssignment could be more flexible for some cases.

One case I have in mind is for property setters.
I often use the following code to have a default implementation for the setter but let overriding it for a custom one.
In this case, it's not an issue to have an inner assignment since there is no  other operation. And putting on multiple lines is useless.

``` haxe
@:isVar
public var value(get, set) : String;
private function get_value() : String { return this.value; }
private function set_value(value : String) : String { return this.value = value; }
```

What do you think about it?

**Comment by fantoine** [comment]
Thanks :)

**Comment by T1mL3arn** [comment]
With vshaxe, this is still an issue with arrow functions

![image](https://user-images.githubusercontent.com/9349164/220065911-098e35e8-8837-4c68-9551-7058911cb3e5.png)
