### ISSUE TITLE
else if block read as else then if

### ISSUE THREAD

**Issue by ibilon** [adireddy/haxe-checkstyle#268]
This

``` haxe
class Test {

    public function test(a:Bool, b:Bool) {
       if (a) {

       }
       else if (!b) {

       }
    }

}
```

gives me

```
./test.hx:7: characters 12-14 : Warning: No braces used for body of "else"
```

but `"tokens"` has `"ELSE_IF"` and no `"ELSE"`.

Is it a bug or did I configure it wrong?

**Comment by Gama11** [comment]
Is this about the behavior or the error message?

**Comment by ibilon** [comment]
Both ? Either it requires me to write

```
else {
  if (!b) {
  }
}
```

which is the wrong thing to do or the message should be

```
Warning: No braces used for body of "else if"
```

which isn't the case.

I can get around this bug by changing the configuration from `aloneorsingle` to `same`,
but then I get errors like this:

```
./src/wx/widgets/Button.hx:20: character 158 : Error: Right curly should not be on same line as left curly
```

the line being

```
@:native("Create")                  @:overload(function(parent:RawPointer<Window>, id:Int, label:ConstCharStar, point:Point, size:Size, style:Int):Bool {})
```

which is true according to `same` but doesn't make sense here on an empty block.

**Comment by adireddy** [comment]
@ibilon Could not able to reproduce this. Can you post the link to your config? Thanks.

**Comment by ibilon** [comment]
Here's the config https://github.com/ianharrigan/hxWidgets/blob/styling/checkstyle.json

I checked and the issue happens with dev too.
