### ISSUE TITLE
Don't ignore all in default config

### ISSUE THREAD

**Issue by skwerlman** [adireddy/haxe-checkstyle#284]
Running checkstyle with `--default-config`, I expect it to output a config with the same behavior as running with no config (i.e. default behavior). Instead, it outputs a config with all checks having `"severity": "IGNORE"`.

Setting up a new project is very tedious when i need to scroll through a ~650 line JSON file manually configuring each option...

**Comment by adireddy** [comment]
We definitely discussed about this earlier. We thought this would give an opportunity to enable few checks at a time and set the severity for each check as per users preference.

Generating a config with default behaviour sounds like a good option but that will still mark a few checks with `IGNORE` and users may not be aware of that.

Another option is to remove `severity` for each check and just set a global `defaultSeverity`

**Comment by skwerlman** [comment]
That argument against enabling all makes sense.

I think I like the second option you propose more, since it has more or less the same effect, but is a bit less tedious.
