### ISSUE TITLE
RedundantModifier enforcePublicPrivate - exclude for interfaces

### ISSUE THREAD

**Issue by markknol** [adireddy/haxe-checkstyle#293]
Hi, I'm adding checkstyle to our projects. It works great so far! Great stuff!

I'm running into this issue:

``` json
{
    "type": "RedundantModifier",
    "props": {
        "enforcePublicPrivate": true
    }
}
```

I want to use this to force "private" to be written out. But it forces me to add "public" in interfaces too, can there be an additional setting to disable that specific check?

**Comment by adireddy** [comment]
@markknol added separate options for `public` and `private`
http://haxecheckstyle.github.io/docs/haxe-checkstyle/redundantmodifier.html

**Comment by Gama11** [comment]
It would probably also be good if you could control this per type, so you could treat interfaces differently for instance.

**Comment by adireddy** [comment]
we could add `tokens` option like other checks do

**Comment by markknol** [comment]
Thanks!
