### ISSUE TITLE
Wrong results for `SpacingCheck` of multiline `if`

### ISSUE THREAD

**Issue by RealyUniqueName** [adireddy/haxe-checkstyle#304]
Such cases will be reported regardless `spaceIfCondition` setting:
```haxe
if(
    true
    && true
    || false
) {}

if (
    true
    && true
    || false
) {}
```

**Comment by RealyUniqueName** [comment]
I guess the reason is compiler reports condition start at `true`, but not at `(`

**Comment by AlexHaxe** [comment]
I think `SpacingCheck` must look at file contents to figure out the correct position of `(`. Just looking at expression positions is not sufficient.
Also: `(` could open on a new line.

Maybe we should convert `SpacingCheck` from AST to TokenTree.
