### ISSUE TITLE
Add auto formatting 

### ISSUE THREAD

**Issue by RealyUniqueName** [adireddy/haxe-checkstyle#314]
Taking into account checktyle already does all the job to find positions, how hard it may be to add auto fixing found positions?

**Comment by AlexHaxe** [comment]
Automatically fixing issues found through checkstyle would be a nice feature, but I don't think checkstyle core is the right place for it. 
It's something an IDE plugin should provide, where issues show up as hints or warnings next to your code and you have a gui to select which auto fix you want to apply.

Also there are a lot of checks where providing an auto fix is not trivial. In name checks for example all you have is a regex, which will tell you that a particular name is not ok. So, how can you create a name that passes your regex test - while preserving as much as possible of its original name?

**Comment by RealyUniqueName** [comment]
Agree

**Comment by carcinocron** [comment]
eslint has the `--fix` option that will automatically fix any style issues that can be fixed.

For any style rule that can't be fixed automatically, eslint will present it as an error.

It's best to automate what we can.

I was considering using this for my project:
```
$ haxelib run checkstyle -s src | wc -l
727
$ haxelib run checkstyle -s src | egrep "space|indent" | wc -l
502
```
but manually fixing 500 whitespace errors by hand seems too tedious.

**Comment by AlexHaxe** [comment]
There is a tool that can fix all whitespace issues: `haxelib run formatter -s src` - but that requires a separate configuration via `hxformat.json`.
Checkstyle and formatter might not be 100% compatible (git version of checkstyle is a lot closer than haxelib version).
