### ISSUE TITLE
Invalid detection of "!" in conditional compilation macros

### ISSUE THREAD

**Issue by RealyUniqueName** [adireddy/haxe-checkstyle#315]
Such code
```haxe
#if !macro
@:autoBuild(some.BuildMacro.build())
#end
interface IInterface {}
```
Produces following report:
```
IInterface.hx:1: characters 4-5 : Info: OperatorWhitespace policy "none" violated by "!"
```

**Comment by RealyUniqueName** [comment]
Thanks for fast fix!

While we are here, wouldn't it be better to treat `~` as unary operator?
Right now it is listed as bitwise according to this: http://haxecheckstyle.github.io/docs/haxe-checkstyle/operatorwhitespace.html

**Comment by AlexHaxe** [comment]
it should work now
