### ISSUE TITLE
Problem running haxe-checkstyle via codeclimate

### ISSUE THREAD

**Issue by ianharrigan** [adireddy/haxe-checkstyle#320]
I have a .hx file that contains styles errors, that, correctly errors when i run locally via CLI, however, when i run via code climate its "all fine" (which it shouldnt have been) and i get the following:

![image](https://cloud.githubusercontent.com/assets/3024242/21283417/24fa448e-c402-11e6-8559-da861833e159.png)

Any thoughts?

**Comment by AlexHaxe** [comment]
I am not very familiar with the codeclimate integration, but out of curiosity I pulled haxeui-core and ran checkstyle in debug mode. 
I found and fixed a bug in checkstyle's parser that gets triggered by https://github.com/haxeui/haxeui-core/blob/master/haxe/ui/macros/ComponentMacros.hx#L150. 
Unfortunately, you now have 31 additional checkstyle issues in haxeui-core.

I don't think my patch fixes your codeclimate issue, so I hope @adireddy can find the time to take a look.

**Comment by adireddy** [comment]
Looks like the issue has been sorted now. Can you try again @ianharrigan 

I also need to release the latest checkstyle version to codeclimate which will take some time.

**Comment by ianharrigan** [comment]
same thing in codeclimate:

```
Invalid field access : getModuleName

Called from checkstyle/Main.hx line 175
Called from checkstyle/Main.hx line 126
Called from checkstyle/Main.hx line 111
Called from checkstyle/Main.hx line 97
Called from checkstyle/Main.hx line 389
```

So is it just a case of CC having to catch up now?

btw, here is the log of CC for "builder pull-engines": 

```
determining required images
docker pull codeclimate-haxe-checkstyle:b422
b422: Pulling from codeclimate/codeclimate-haxe-checkstyle
6ffe5d2d6a97: Pulling fs layer
f4e00f994fd4: Pulling fs layer
e99f3d1fc87b: Pulling fs layer
a3ed95caeb02: Pulling fs layer
897ff80d6cdd: Pulling fs layer
ab119f701ebc: Pulling fs layer
59b90d362778: Pulling fs layer
dfe1054b8dbf: Pulling fs layer
fb0fa66bb783: Pulling fs layer
d81b536824c0: Pulling fs layer
c9ee28b74e83: Pulling fs layer
c69c4a11ccc6: Pulling fs layer
89835b6be4f4: Pulling fs layer
4888a728ba0f: Pulling fs layer
7b40d335cf84: Pulling fs layer
4405d68f881e: Pulling fs layer
30f78d6e4a79: Pulling fs layer
a3ed95caeb02: Waiting
897ff80d6cdd: Waiting
ab119f701ebc: Waiting
59b90d362778: Waiting
dfe1054b8dbf: Waiting
fb0fa66bb783: Waiting
d81b536824c0: Waiting
c9ee28b74e83: Waiting
c69c4a11ccc6: Waiting
89835b6be4f4: Waiting
4888a728ba0f: Waiting
7b40d335cf84: Waiting
4405d68f881e: Waiting
30f78d6e4a79: Waiting
e99f3d1fc87b: Verifying Checksum
e99f3d1fc87b: Download complete
a3ed95caeb02: Verifying Checksum
a3ed95caeb02: Download complete
f4e00f994fd4: Verifying Checksum
f4e00f994fd4: Download complete
ab119f701ebc: Verifying Checksum
ab119f701ebc: Download complete
59b90d362778: Verifying Checksum
59b90d362778: Download complete
dfe1054b8dbf: Verifying Checksum
dfe1054b8dbf: Download complete
fb0fa66bb783: Verifying Checksum
fb0fa66bb783: Download complete
d81b536824c0: Verifying Checksum
d81b536824c0: Download complete
c9ee28b74e83: Verifying Checksum
c9ee28b74e83: Download complete
c69c4a11ccc6: Verifying Checksum
c69c4a11ccc6: Download complete
89835b6be4f4: Verifying Checksum
89835b6be4f4: Download complete
4888a728ba0f: Verifying Checksum
4888a728ba0f: Download complete
7b40d335cf84: Verifying Checksum
7b40d335cf84: Download complete
897ff80d6cdd: Verifying Checksum
897ff80d6cdd: Download complete
4405d68f881e: Verifying Checksum
4405d68f881e: Download complete
30f78d6e4a79: Verifying Checksum
30f78d6e4a79: Download complete
6ffe5d2d6a97: Verifying Checksum
6ffe5d2d6a97: Download complete
6ffe5d2d6a97: Pull complete
f4e00f994fd4: Pull complete
e99f3d1fc87b: Pull complete
a3ed95caeb02: Pull complete
897ff80d6cdd: Pull complete
ab119f701ebc: Pull complete
59b90d362778: Pull complete
dfe1054b8dbf: Pull complete
fb0fa66bb783: Pull complete
d81b536824c0: Pull complete
c9ee28b74e83: Pull complete
c69c4a11ccc6: Pull complete
89835b6be4f4: Pull complete
4888a728ba0f: Pull complete
7b40d335cf84: Pull complete
4405d68f881e: Pull complete
30f78d6e4a79: Pull complete
Digest: sha256:76c2306b1495e81b4ed9f680417655618967f0e0473981c48090df6cc732a591
Status: Downloaded newer image for registry.prod.codeclimate.net/codeclimate/codeclimate-haxe-checkstyle:b422
```

**Comment by adireddy** [comment]
I think I figured out the issue @ianharrigan.

Code climate has checkstyle v2.1.3 which doesn't have `UnusedLocalVar` check. If you remove that check from your config it should be fine.

Releasing new versions to code climate will take time as I need to send an email to them. For future releases, I will have to make sure to release to haxelib and codeclimate at the same time to avoid this kind of issues.

**Comment by ianharrigan** [comment]
OK, that seems to have run now... however, im getting 291 issues (!) where locally i get around 4... Presumably because the versions are so mismatched? (for example, it doesnt have seemed to ignore anything in "exclude" - maybe thats new?)...

I guess ill put back in the UnusedLocalVar for now until the CC version has been brought up to date. Should i close this issue?

Many thanks for all the help!

**Comment by adireddy** [comment]
No problem. I already sent an email to them. Let's keep this issue open until it's updated in code climate.

**Comment by ianharrigan** [comment]
Any news on CC regarding this yet btw? (just wondering) :)

**Comment by adireddy** [comment]
No news yet. Christmas break doesn't help either :)

**Comment by ianharrigan** [comment]
Cool... was just checking... thanks! And happy xmas!

**Comment by ianharrigan** [comment]
Hello again! Wondering if there was any news on this? Noticed a new checkstyle lib was released? So was hoping maybe this can be closed?

Thanks in advance,
Ian

**Comment by adireddy** [comment]
Unfortunately no @ianharrigan. I pinged code climate again after the release today but no response yet. So lets keep this open until they respond.

**Comment by ianharrigan** [comment]
Fair enough... sorry to constantly ask! Just thought maybe there had been some motion and this got overlooked. :)

Thanks again!

**Comment by adireddy** [comment]
No problem :)

**Comment by adireddy** [comment]
@ianharrigan Just got an update from Code Climate. They are looking into it now. Hopefully will be updated soon.

**Comment by adireddy** [comment]
@ianharrigan I can confirm that it's up to date in code climate now.

you should see `docker pull codeclimate-haxe-checkstyle:b527`

Docker link for future ref: https://hub.docker.com/r/codeclimate/codeclimate-haxe-checkstyle/

**Comment by ianharrigan** [comment]
Thanks loads for the update, i havent fully "had a play" yet, but im sure its all great. Thanks once again (and no more spamming from me! promise!) 

Ian
