### ISSUE TITLE
TokenTreeBuilder crash with .new

### ISSUE THREAD

**Issue by Gama11** [adireddy/haxe-checkstyle#323]
Both of these are valid Haxe code, but crash with `bad token Kwd<KwdPrivate> != POpen`:

```haxe
@:allow(SomeClass.new) class Test {}
```

```haxe
class Test {
	var constructor = SomeClass.new;
}
```

Note: could very well be a regression, I don't think I ran into this before with Flixel.

**Comment by Gama11** [comment]
Note: this could very well be a regression, I didn't run into this before with Flixel...

**Comment by Gama11** [comment]
@AlexHaxe Holy crap, that was fast! :D

**Comment by AlexHaxe** [comment]
Thanks, I just happened to check my mails at the right time and was curious.

**Comment by Gama11** [comment]
Heh, haxeparser has the same issue: https://github.com/Simn/haxeparser/issues/38
