### ISSUE TITLE
BlockFormat check: allow comments after opening brace

### ISSUE THREAD

**Issue by nadako** [adireddy/haxe-checkstyle#33]
Hi! Thanks for your tool, it's really one of the things Haxe needs most, I am looking into integrating it into our company workflow, however I found quite a bit of code like the following:

``` haxe
if (someComplexCheck) { // description of what the check actually means
   // ...
}
```

And I think it's not unreasonable to place those comments after the opening brace, so do you think checkstyle could have an option for the `BlockFormat` checker to allow comments after the opening brace?

**Comment by AlexHaxe** [comment]
`BlockFormat` had some support for comments, but it was broken, it should work now on the `dev` branch.
`dev` also contains a few new tests that are based on an experimental token tree builder, which might break on some code fragments. Let us know, if you see stack traces when activating them (if you can pinpoint the location and/or provide code that breaks, that would be helpful).

**Comment by nadako** [comment]
Thanks, I will. Oh, while we're at it, I also had problems with `import haxe.extern.EitherType` - probably because haxeparser (checkstyle uses it, right?) doesn't allow `extern` (and probably `macro`) in a type path, however Haxe allows it. cc @Simn

**Comment by adireddy** [comment]
@nadako just released `BlockFormat` bug fix to [haxelib](http://lib.haxe.org/p/checkstyle/1.2.1/) v1.2.1
