### ISSUE TITLE
ModifierOrderCheck includes function body in position

### ISSUE THREAD

**Issue by chipshort** [adireddy/haxe-checkstyle#332]
The "characters" part of the error provided when ModifierOrderCheck fails, includes the whole function body.
Ironically, it does not include the modifier itself.
Example: `src/CheckStyleMacro.hx:16: characters 21-1121 : Info: "build" modifier order is invalid (modifier: "MACRO")`
I am currently writing a FlashDevelop plugin to further integrate checkstyle into FD (including underlining the positions) and this ends up very ugly:

![underline](https://cloud.githubusercontent.com/assets/4466937/24612660/32a57634-1886-11e7-9c5d-6eda6cf207f8.png)

Ideally, only the modifier should be included, but I think just including the function header without the body would be good enough. I tried to look into it myself, but the only thing I could come up with was to use the function body expr's min as max for the warning, which is probably not so nice.

**Comment by AlexHaxe** [comment]
I sort of fixed the issue, by using position from function body. Unfortunately AST-based checks have limited access to position information, because most data structures don't include them.

A rewrite as a token tree check would allow for a more precise warning.
