### ISSUE TITLE
[haxe4] get a new haxeparser library with Haxe 4 support

### ISSUE THREAD

**Issue by AlexHaxe** [adireddy/haxe-checkstyle#338]
- short lambas / arrow functions
- final keyword

**Comment by AlexHaxe** [comment]
waiting on https://github.com/Simn/haxeparser/pull/50

**Comment by cmandlbaur** [comment]
I noticed that a few checks weren't running on some of our code and realised that due to parsing errors relating to arrow functions. I see the upstream haxeparser PR has landed, any idea when this will be resolved?

**Comment by AlexHaxe** [comment]
While running some final tests I found and fixed a few null pointer exceptions for C++ builds, and opened a PR in haxeparser which probably gets accepted in a few hours.

Once that PR is in, I guess I have no more excuses but to make a fresh release of checkstyle...

**Comment by cmandlbaur** [comment]
Thanks, appreciate the effort!

**Comment by AlexHaxe** [comment]
In case you haven't seen it already, I released checkstyle 2.5.0 yesterday evening. An updated VSCode extension is still in the works. For codeclimate integration I'll have to set up a new docker image and run some tests, before I can submit a new version.
