### ISSUE TITLE
Token tree builder

### ISSUE THREAD

**Issue by adireddy** [adireddy/haxe-checkstyle#34]
Just ran dev branch on one of my projects and saw the following. Tested `HiddenFieldCheck` and `AvoidStarImport`.

```
Error: LINE - 1: Checker - Check HiddenField failed: bad token POpen != Semicolon
Stacktrace: 
Called from TokenStream.hx line 46
Called from TokenTreeBuilder.hx line 258
Called from TokenTreeBuilder.hx line 116
Called from TokenTreeBuilder.hx line 52
Called from TokenTreeBuilder.hx line 41
Called from TokenTreeBuilder.hx line 23
Called from Checker.hx line 43
Called from checks/HiddenFieldCheck.hx line 28
Called from checks/Check.hx line 22
Called from Checker.hx line 155
```

Let me know if you need any more info.

I also created `token-tree` branch so that we can use `dev` branch for minor releases. Please use `token-tree` branch to continue your work.

**Comment by AlexHaxe** [comment]
can you attach some code? It must be a var field / member definition in your class/interface/abstract that breaks, one without assignment operator.

**Comment by adireddy** [comment]
Found the issue. It's failing on setter/getter definitions.

Example:
`public var anchor(default, set):Point;`

**Comment by AlexHaxe** [comment]
that should fix it

**Comment by adireddy** [comment]
fixed

**Comment by adireddy** [comment]
Found another issue:

Switch statement without parenthesis is breaking. I don't use it like that but found issue in some old code base.
http://try.haxe.org/#F3958

```
Error: LINE - 1: Checker - Check AvoidStarImport failed: bad token Const(CIdent(pos)) != POpen
Stacktrace: 
Called from TokenStream.hx line 46
Called from TokenTreeBuilder.hx line 441
Called from TokenTreeBuilder.hx line 553
Called from TokenTreeBuilder.hx line 358
Called from TokenTreeBuilder.hx line 416
Called from TokenTreeBuilder.hx line 294
Called from TokenTreeBuilder.hx line 119
Called from TokenTreeBuilder.hx line 52
Called from TokenTreeBuilder.hx line 41
Called from TokenTreeBuilder.hx line 23
Called from Checker.hx line 43
Called from checks/AvoidStarImportCheck.hx line 19
Called from checks/Check.hx line 22
Called from Checker.hx line 155
```

**Comment by AlexHaxe** [comment]
switch expressions with and without `()` should work now

**Comment by adireddy** [comment]
:+1: 

Tested on a couple of projects without any issues.
