### ISSUE TITLE
Jenkins Parsing error

### ISSUE THREAD

**Issue by dmouton** [adireddy/haxe-checkstyle#342]
Hi,
I use this command to generate a report :
`haxelib run checkstyle -s src/com/ -p report.xml -c checkstyle.json`

But the Jenkins Checkstyle plugins doesn't like my report.xml file 
`Parsing of file /var/lib/jenkins/workspace/SakuraHx-next/report.xml failed due to an exception: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1`

My report.xml look like plain text file

Checkstyle 2.1.12

**Comment by dmouton** [comment]
[report.xml.zip](https://github.com/HaxeCheckstyle/haxe-checkstyle/files/1055386/report.xml.zip)

**Comment by AlexHaxe** [comment]
Checkstyle defaults to text reporter, to use the xml reporter you need to add `-r xml` to your command line
