### ISSUE TITLE
MemberName tokens not working ?

### ISSUE THREAD

**Issue by Thanadev** [adireddy/haxe-checkstyle#343]
Hi,
I want to use my own checkstyle for naming class members.

`{
    "type": "MemberName",
    "props": {
        "severity": "ERROR",
        "format": "^a$",
        "tokens": [
            "PUBLIC"
        ]
    }
}
`

But the format is totally uneffective except if i omit tokens.
Did i do something wrong ?

**Comment by AlexHaxe** [comment]
Hi,
sorry for the delayed answer:

`PUBLIC` and `PRIVATE` tokens only work in combination with either `CLASS` or `ABSTRACT`, they cannot stand alone. If tokens just contains `CLASS` or `ABSTRACT` that would also fail.
I have updated the documentation of `MemberNameCheck` (see https://haxecheckstyle.github.io/docs/haxe-checkstyle/membername.html)

**Comment by Gama11** [comment]
That seems a bit unexpected.. Couldn't that be fixed fairly easily? I.e. if there's only "PUBLIC", apply that to both "CLASS" and "ABSTRACT", if there's only "CLASS", assume that that should apply to both "PUBLIC" and "PRIVATE".

**Comment by AlexHaxe** [comment]
ok, I think I fixed it now...

It should now work with just `CLASS` or just `PUBLIC` and you still can have different definitions for `["CLASS", "PUBLIC"]` and `["ABSTRACT", "PUBLIC"]`
