### ISSUE TITLE
spaces around "!"

### ISSUE THREAD

**Issue by ivan-slepchenko** [adireddy/haxe-checkstyle#346]
Hi. I have an issue
SneakPeekEndDialogViewHelper.hx:61: characters 7-8 : Info: OperatorWhitespace policy "none" violated by "!"

for the line:
if ( !this.visible )

but I need it to be like this. I need empty spaces after brackets.
if I will change to 
if (!this.visible ) -  the warn will disappears, but I don't want it that way :)

Please help

**Comment by AlexHaxe** [comment]
Hi, 

I tried to reproduce your issue with current dev, but it seems to work like you want it to. I have added a testcase and it's green. 

So, what version of haxe checkstyle do you use, have you tried the latest dev version and what operating system are you on (I am running Linux - it should not make a difference but just in case)?

**Comment by AlexHaxe** [comment]
It should work now. 

A helper function didn't properly detect `!this` (worked fine with `!that`), because `this` is a keyword and needs special treatment. It was simply looking at the wrong side of `!`, that's why it worked when you removed all spaces.
