### ISSUE TITLE
Allow pure regex or wildcards in the exclude string

### ISSUE THREAD

**Issue by pypmannetjies** [adireddy/haxe-checkstyle#349]
At the moment the checkstyle excludes do not allow a pure regex pattern inside excludes. It is prepending the source path and then appending the file it's checking to the checkstyle pattern. You should be able to pass in a wildcard or regex pattern. 

For example I want to exclude all classes that contain "CheckThisOut" in the classname. 

```
"exclude": {
        "AvoidStarImport": [
            ".*CheckThisOut"
        ]
    }
```

But it's not possible because the resulting regex (after all the changes) looks like this:

`Folder:Folder:src::*CheckThisOut:.*?SomeOtherClassName$`

Notice that the . in the pattern has been changed to a colon and the class that is being checked is appended. 

I would suggest we only apply the path changes to the input if the path option is specified. Otherwise treat it like pure regex.

**Comment by pypmannetjies** [comment]
How can we do a release of the latest version? :)

**Comment by AlexHaxe** [comment]
I think we would have to update the setup section of checkstyle docs and than we need an @adireddy for pressing the actual release button. 
I don't know much about his schedule, so it might take a few days before he has the time to do it.

**Comment by adireddy** [comment]
hey @pypmannetjies, will do the release today. Can you make sure you update the docs here please http://haxecheckstyle.github.io/docs/haxe-checkstyle/setup.html#exclude-packagesclasses

**Comment by pypmannetjies** [comment]
Hey @adireddy, thanks! Will do, but I'm not too sure where those files live? Are they in the repo?

**Comment by AlexHaxe** [comment]
repo: https://github.com/HaxeCheckstyle/docs
