### ISSUE TITLE
ExitcodeReporter causes an exit for non Error

### ISSUE THREAD

**Issue by Enzyoh** [adireddy/haxe-checkstyle#354]
When including the **-exitcode** flag, we are gettting the checkstyle process stopping when **Warnings** occur. Can we make this process only exit when an **Error** occur.

Possibly change the following in **haxe-checkstyle/src/checkstyle/reporter/ExitCodeReporter.hx**

`public function addMessage(m:CheckMessage) {
		failCheckCount++;
	}`

to 

`public function addMessage(m:CheckMessage) {
            if(m.severity == ERROR){
		failCheckCount++;
            }
	}`

**Comment by adireddy** [comment]
done in v2.1.15
