### ISSUE TITLE
Wrong curly braces issue reporting with macro reification.

### ISSUE THREAD

**Issue by RealyUniqueName** [adireddy/haxe-checkstyle#37]
Following code will raise an issue, but such usage of curly is correct:

``` haxe
var str = 'Hello, world';
var expr = macro for (i in 0...10) trace($v{str});
```

Issue: 

```
Warning: LINE - 148: Left curly should be at EOL (only linebreak or comment after curly)
```

Macro reification can be determined by `$` followed by one or zero characters. e.g.:

```
$varName;
$a{varName};
${varName.fieldVar};
```

**Comment by AlexHaxe** [comment]
Should work in `token-tree` branch.

Note: some of the new tests and functionality in `token-tree`branch is still experimental. Feel free to open new issues for any problem you might encounter.

**Comment by RealyUniqueName** [comment]
Thanks. It works.
