### ISSUE TITLE
Array in object declaration fails TokenTreeBuilder

### ISSUE THREAD

**Issue by chipshort** [adireddy/haxe-checkstyle#370]
```haxe
class Test2
{
    var t = {
        arg: [2, 3]
    };
}
```
This fails with:
```
bad token BkClose != BrClose
Stacktrace:
Called from checkstyle.token.TokenStream::consumeTokenDef line 51
Called from checkstyle.token.walk.WalkObjectDecl::walkObjectDecl line 20
Called from checkstyle.token.walk.WalkStatement::walkStatement line 39
Called from checkstyle.token.walk.WalkStatement::walkStatement line 73
Called from checkstyle.token.walk.WalkVar::walkVar line 25
Called from checkstyle.token.walk.WalkClass::walkClassBody line 34
Called from checkstyle.token.walk.WalkClass::walkClass line 16
Called from checkstyle.token.walk.WalkType::walkType line 7
Called from checkstyle.token.walk.WalkFile::walkFile line 25
Called from checkstyle.token.TokenTreeBuilder::buildTokenTree line 11
```
The problem seems to happen somewhere in this case, because `walkTypeNameDef` is consuming the `BkOpen` away:
https://github.com/HaxeCheckstyle/haxe-checkstyle/blob/v2.1.16/src/checkstyle/token/walk/WalkStatement.hx#L73

**Comment by AlexHaxe** [comment]
I looked at WalkObjectDecl and found it needed some refactoring. I came up with #372 which looks a lot more complicated than your solution in #371. Both produce a similar token tree structure, but I feel like #371 only circumvents the issue. It's an object declaration so it should be handled as such.
