### ISSUE TITLE
 Unknown check: BlockFormat

### ISSUE THREAD

**Issue by RealyUniqueName** [adireddy/haxe-checkstyle#39]
I'm trying `token-tree` branch and get this error:

```
Main.hx:40: Unknown check: BlockFormat
```

**Comment by AlexHaxe** [comment]
I removed `BlockFormat`, since `EmptyBlock`, `LeftCurly` and `RightCurly` cover its checks, but provide a bit more flexibility.
So you need to remove `BlockFormat` from your config file and add an `EmptyBlock` entry.
