### ISSUE TITLE
[TokenTreeBuilder] Parsing errors

### ISSUE THREAD

**Issue by chipshort** [adireddy/haxe-checkstyle#396]
The TokenTreeBuilder fails in a few cases after the changes in b510ac8faaaf4e440c4477f74f8b4b4b19ad7ef9.
Here are a few examples:
```haxe
//fails with: bad token Comma != BrClose
var test = switch a
{
    case 3: {a: 1, b: 2};
    default: {a: 0, b: 2};
}
```
And a more complicated one with conditional compilation:
```haxe
//fails with: bad token Kwd(KwdFunction) != DblDot
return {
    #if js
    something:
    #else
    somethingelse:
    #end
    function (e)
    {
        e.preventDefault();
        callback();
    }
};
```

Also, I am not really happy with this function: https://github.com/HaxeCheckstyle/haxe-checkstyle/blob/b510ac8faaaf4e440c4477f74f8b4b4b19ad7ef9/src/checkstyle/token/walk/WalkBlock.hx#L37-L46
It is not possible to know if something is a block or an object before actually parsing it in most cases.
One example where the function would return wrong results:
```haxe
return {
    doSomething();
    1;
}
```
The same works for the `BkOpen` case too, and basically any other case where some kind of value is needed.

**Comment by AlexHaxe** [comment]
yes, we should rethink parsing of blocks and object declarations. 
It might not even matter whether we are parsing a block or an object declaration, it only matters later when running checks.
