### ISSUE TITLE
Single line class declaration when no fields needed

### ISSUE THREAD

**Issue by RealyUniqueName** [adireddy/haxe-checkstyle#40]
Is there a way to make one line type declaration code pass `LeftCurly` checks when declared type has no fields?

```
class MyChild1 extends MyParent {}
class MyChild2 extends MyParent {}
class MyChild3 extends MyParent {}
```

I have following rule which fails on above code:

```
{
            "type"  : "LeftCurly",
            "props" : {
                "severity" : "WARNING",
                "option"   : "nl",
                "tokens"   : [
                    "CLASS_DEF",
                    "ENUM_DEF",
                    "ABSTRACT_DEF",
                    "INTERFACE_DEF"
                ]
            }
        }
```

Produces these errors:

```
Warning: LINE - 12: LeftCurly - Left curly should be on new line (only whitespace before curly)
Warning: LINE - 13: LeftCurly - Left curly should be on new line (only whitespace before curly)
Warning: LINE - 14: LeftCurly - Left curly should be on new line (only whitespace before curly)
```

**Comment by AlexHaxe** [comment]
Well, you can always add `@SuppressWarnings("checkstyle:LeftCurly")`, but right now there is no option to allow `{}` in LeftCurly.

**Comment by RealyUniqueName** [comment]
`@SuppressWarnings("checkstyle:LeftCurly")` does not work in this case:

```
var definition = macro class Font extends flash.text.Font {}
```

**Comment by Gama11** [comment]
This seems like something that should be sorted out before the token-tree branch is merged (#51), since `BlockFormat` was able to handle this and it doesn't exist there anymore.

**Comment by AlexHaxe** [comment]
LeftCurly now has an option `ignoreEmptySingleline` , which will skip all instances of `{}`.
There is also EmptyBlock check, which can enforce `{}` notation of empty blocks.
Both checks are available in token-tree branch.

**Comment by adireddy** [comment]
@AlexHaxe Did you commit this change with `ignoreEmptySingleline`? Couldn't find it anywhere.

**Comment by AlexHaxe** [comment]
I only committed it to token-tree branch: https://github.com/adireddy/haxe-checkstyle/commit/5b50e3f816a5299a6518f1b5d5fa55819f421de3

**Comment by adireddy** [comment]
ok
