### ISSUE TITLE
Indentation issues in checkstyle's Main.hx

### ISSUE THREAD

**Issue by AlexHaxe** [adireddy/haxe-checkstyle#458]
currently checkstyle has the following messages in it's selftest:

```
src/checkstyle/Main.hx:63: characters 0-4 : Indentation - Info: Indentation mismatch: expected: "\t\t\t\t\t"[5], actual: "\t\t\t\t"[4]
src/checkstyle/Main.hx:64: characters 0-4 : Indentation - Info: Indentation mismatch: expected: "\t\t\t\t\t"[5], actual: "\t\t\t\t"[4]
src/checkstyle/Main.hx:65: characters 0-4 : Indentation - Info: Indentation mismatch: expected: "\t\t\t\t\t"[5], actual: "\t\t\t\t"[4]
src/checkstyle/Main.hx:79: characters 0-4 : Indentation - Info: Indentation mismatch: expected: "\t\t\t"[3], actual: "\t\t\t\t"[4]
```
which seems to enforce
```
	@doc("Set reporter output path") ["-p", "--path"] => function(path:String) {
			XML_PATH = path;
			JSON_PATH = path;
			TEXT_PATH = path;
	},
	@doc("Adds error messages for files that checkstyle fails to parse") ["-show-parser-errors"] => function ()
	ReporterManager.SHOW_PARSE_ERRORS = true,
```

@RblSb do you want to take a look?

**Comment by RblSb** [comment]
Hmm, for some reason I did not see this through `haxelib run checkstyle -s src` in`src/checkstyle/` until I placed `Main.hx` in `src/`. Prior to this action, the source was not checked.

**Comment by AlexHaxe** [comment]
I think messages from lines 63-64 have been in there for some time now, I suspect a change in tokentree might have caused it. 
Line 79 is a new one.

`haxelib run checkstyle -s src` doesn't work for me, since I have a local `.haxelib` folder, so I'm usually running `haxe buildAll.hxml` or at least `haxe buildTest.hxml`. 
They take their time and currently they only run a self check in Haxe 3.x (Haxe 4's eval will stop after unittests), but that makes sure everything works and you get schema updates (`buildAll.hxml`). 
And any new checkstyle violation will make `resources/static-analysis.txt` show up in your change list.

**Comment by RblSb** [comment]
in this block
```haxe
@doc("Set reporter output path") ["-p", "--path"] => function(path:String) {
	XML_PATH = path;
	JSON_PATH = path;
	TEXT_PATH = path;
},
```
`BkOpen` has incorrect indentation block from `@doc` line+1 (ok) to `TEXT_PATH` line (wrong), as if `BkOpen` is terminated on `BrClose`.
blockStart.pos.min - blockEnd.pos.min = 64 characters, not sure if `blockEnd.pos.min` wrong or it's an `checker.getLinePos` bug.

**Comment by AlexHaxe** [comment]
Thanks for looking into it!
It turned out to be a problem with how the tokentree is structured in that case, `=>` is a child of `[`, so `increaseBlockIndent` would take `=>` as blockEnd, instead of `]`.

I am considering to replace checkstyle's indentation logic with the one from formatter somewhere in the future, but currently it's not really compatible. So for now we're stuck with two different indentation implementations.
