### ISSUE TITLE
Check for empty lines between doc comment and field

### ISSUE THREAD

**Issue by Gama11** [adireddy/haxe-checkstyle#47]
I'd like to detect instances where of empty lines between a doc comment and a class field to disallow that:

``` haxe
/**
 * Some doc.
 */ 

var example:Int;
```

Perhaps as an extra option for `EmptyLines`?

**Comment by adireddy** [comment]
added `allowEmptyLineAfterComment` option to `EmptyLinesCheck` in dev branch.

Default is `true`

**Comment by Gama11** [comment]
Awesome, thanks! :+1:
