### ISSUE TITLE
Different regular expression for enum names than what is officially documented

### ISSUE THREAD

**Issue by khalyomede** [adireddy/haxe-checkstyle#504]
## Description

Running checkstyle on a code base declaring enums raise Infos level message on enum format using what seems to be a different regular expression than the one used on the official documentation.

## Steps to reproduce

1. Copy this code 

```haxe
enum Severity {
  Emergency;
  Alert;
  Critical;
  Error;
  Warning;
  Notice;
  Info;
  Debug;
}

class Main {

  public static function main() {
    final severity = Erorr;
  }
}
```

2. Run checkstyle on this file
3. An info level message about casing of enum values is shown

## Expected behavior

The naming for enums uses a PascalCase regular expression instead of camelCase.

## Actual behavior

This error is shown:

> Invalid enum member signature "Emergency" (name should be "~/^[a-z][a-zA-Z0-9]*$/")

**Comment by AlexHaxe** [comment]
when there is no explicit configuration via `checkstyle.json` MemberName check applies the same regex to all member fields regardless of location / type. 

what you want is a dedicated configuration for enum fields, something like this (yes, you can add a check multiple times with different settings):
```json
{
	"props": {
		"ignoreExtern": true,
		"format": "^[A-Z][a-zA-Z0-9]*$",
		"tokens": [
			"ENUM"
		]
	},
	"type": "MemberName"
},
{
	"props": {
		"ignoreExtern": true,
		"format": "^[a-z][a-zA-Z0-9]*$",
		"tokens": [
			"CLASS",
			"PUBLIC",
			"PRIVATE",
			"TYPEDEF"
		]
	},
	"type": "MemberName"
}
```

**Comment by khalyomede** [comment]
Very cool! I tried to put it in a `checkstyle.json` at the root of my directory, and when trying to run the command I have encoutered this error:

```bash
$ haxelib run checkstyle --source src
Config has unknown field 'props'
```

Do you know if the file requires a specific format to include these rules in?

(I'm using version 2.7.0)

**Comment by AlexHaxe** [comment]
sorry, I assumed you already had some sort of a `checkstyle.json`, so I only copied some parts related to MemberName check from my config.

a more complete sample config looks like that:
```json
{
    "defaultSeverity": "INFO",
    "checks": [
        {
            "props": {
                "format": "^[A-Z][a-zA-Z0-9]*$",
                "tokens": [
                    "ENUM"
                ]
            },
            "type": "MemberName"
        },
        {
            "props": {
                "format": "^[a-z][a-zA-Z0-9]*$",
                "tokens": [
                    "CLASS",
                    "PUBLIC",
                    "PRIVATE",
                    "TYPEDEF"
                ]
            },
            "type": "MemberName"
        }
    ]
}
```
beware: if you use above sample config, then you will only check for MemberName, all other checks will not run unless you add them to your config.

if you are using VSCode with haxe checkstyle extension it comes with a JSON schema so you should get completion and suggestions when editing `checkstyle.json`.

**Comment by khalyomede** [comment]
Perfect, I am using VSCode so it already warned me the structure was not alright. Thank you so much for providing the complete checkstyle.json! I'm going to close this issue as I have a working solution now. Keep up the good work.
