### ISSUE TITLE
No Fail with Github Workflow

### ISSUE THREAD

**Issue by inc0der** [adireddy/haxe-checkstyle#509]
I noticed when using checkstyle with a GitHub workflow that the step won't fail when checkstyle detects issues. I'm fairly new to GitHub workflows so I could be missing something obvious but I figured I would at least create an issue to start the discussion.

**Examples:**
You can check out the 1st failed workflow [here](https://github.com/inc0der-forks/origami-devtools/runs/3376955827?check_suite_focus=true) under `npm run ci-checkstyle`

I have another failed run [here ](https://github.com/inc0der-forks/origami-devtools/runs/3377153587?check_suite_focus=true) same section, but this time its an actual error due to a bad character within the `checkstyle`.json`

Both examples fail within the CI but the actual steps succeed and the GitHub workflow passes.

**Comment by AlexHaxe** [comment]
add `--exitcode` to your checkstyle command to make it fail with a non zero exitcode indicating the number of errors found (warning and info level issues don't increase exitcode)
