### ISSUE TITLE
Add check for CommentedCode

### ISSUE THREAD

**Issue by EliteMasterEric** [adireddy/haxe-checkstyle#511]
Detects valid Haxe code which is contained within a comment.

Programmers should not comment out code as it bloats programs and reduces readability. Unused code should be deleted and can be retrieved from source control history if required.

A valid comment is one which contains additional context or otherwise does not contain valid Haxe code.

# Configuration

```
{
    "type": "CommentedCode",
    "props": {
        "severity": "ERROR"
    }
}
```

# Invalid

```
var value = (event.keyCode != null) ? (event.keyCode == KeyCode.ENTER) ? 10 : 5 : 1;
// trace(value);
```

```
var value = 1;
/**
if (event.keyCode != null) {
    value = (event.keyCode == KeyCode.ENTER) ? 10 : 5;
}
**/
```

```
/**
  * trace(value);
  */
var value = 1;
```

# Valid

```
// This is a test.
var value = 1;
```

```
// Use the function like this: trace(value);
var value = 1;
```

```
/**
  * Use the function like this:
  * trace(value);
  */
var value = 1;
```

**Comment by AlexHaxe** [comment]
fixed by #512
