### ISSUE TITLE
Add check for import order

### ISSUE THREAD

**Issue by EliteMasterEric** [adireddy/haxe-checkstyle#519]
A check should exist to standardize the order and categorization of imports.

For example, a user may develop a pull request which inadvertently reorders the list of imports in a class, causing unnecessary mental load as maintainers attempt to determine if new imports were actually added.

## Proposal

*This proposal is based on the JavaScript library [prettier-plugin-sort-imports](https://github.com/trivago/prettier-plugin-sort-imports).*

The new check `ImportOrder` standardizes the order and categorization of imports in a Haxe class.

With this check enabled, Haxe Checkstyle will require the user to sort their imports. The user can use Regex for configuration, and natural sort order will be used where there are ambiguities.

```
{
  checks: [
    {
      "type": "ImportOrder",
      "props": {
        "order": [
          "^(lime|openfl)$",
          "flixel",
          ".*"
        ],
        "separateGroups": true,
        "severity": "NOTICE"
      }
    }
  ]
}
```

`ImportOrder` has the following parameters:

- `order`: Specify an array of regular expressions defining groups of imports.
- `separateGroups`: Specifies that a newline should separate each group of imports.
- `severity`: The standard severity specification.

The example configuration produces this result:
```
import lime.Test;
import openfl.Test;

import flixel.FlxG;
import flixel.Test;

import mygame.Test;
```

Notes:
- Any imports not matched by any regular expression should be placed at the end, in natural sort order.
- Having an fix action available in the VSCode extension would be ideal.

**Comment by AlexHaxe** [comment]
Haxe language server comes with a sort / organize imports feature (see [Code-Action sort imports](https://github.com/vshaxe/vshaxe/wiki/Code-Actions#sort-importsusings))
so any checkstyle check should support import-sorting modes built into Haxe lsp

**Comment by EliteMasterEric** [comment]
Thank you! This provides what I was looking for. The important takeaway is the existence of Right Click -> Source Actions -> Sort imports/usings

The ability to customize import order could be nice I guess, but not really necessary.
