### ISSUE TITLE
FlashDevelop-compatible character position output

### ISSUE THREAD

**Issue by Gama11** [adireddy/haxe-checkstyle#55]
For Flixel, [I've setup a FlashDevelop `.hxproj` file to run checkstyle](https://github.com/HaxeFlixel/flixel/tree/dev/tests/checkstyle), which means the results are parsed and appear in the results panel, which is quite convenient (a double click takes you to the file at the specified line number).

![](http://i.imgur.com/n84tnE7.png)

However, this only works for the line numbers, not character positions - FlashDevelop expects a different format there.

Here's a Haxe error message (FD can handle this format):

```
C:/HaxeToolkit/haxe/lib/flixel/git/flixel/input/FlxBaseKeyList.hx:24: characters 1-8 : Unexpected private
```

I guess the question is mostly whether the output can simply be changed in the current text reporter, or if there's a need for a new reporter to maintain backwards compatibility.

**Comment by adireddy** [comment]
That's awesome @Gama11 :+1: Hope I can do the same for intelliJ :)

I think it's better to add a new reporter for flash develop. Can you raise a PR with your changes pls?

**Comment by Gama11** [comment]
To clarify, there are no changes required the get the result I showed in the screenshot, that works out of the box with `-r text`. The thing that's missing is compatible character positions, line numbers work - I can look into making that work.

I'm not sure about the name for the new reporter. `flashdevelop` seems too specific, any Haxe IDE that can handle the compiler's error messages should be able to handle this as well.

**Comment by adireddy** [comment]
Got it. If the changes are minimal let's change the text reporter then. Let me know when you make character positions work.

**Comment by Gama11** [comment]
Btw, 2 tests are currently failing for me when running the `build.hxml` (both from `FileLengthCheckTest`). Is that expected? The travis is green..

**Comment by adireddy** [comment]
Which branch are you on? I just commited a few updates to `dev` branch and I can confirm that it has no issues.

**Comment by Gama11** [comment]
I'm on latest `dev` as well. Here's the output:

```
* FileLengthCheckTest::testConfigurableFileLength()
ERR: FileLengthCheckTest.hx:25(FileLengthCheckTest.testConfigurableFileLength) -
 expected 'Too many lines in file (> 40)' but was ''

Called from C:\HaxeToolkit\haxe\std/haxe/unit/TestCase.hx line 69
Called from test/FileLengthCheckTest.hx line 25
Called from <builtin> line 1
Called from C:\HaxeToolkit\haxe\std/neko/_std/Reflect.hx line 58
Called from C:\HaxeToolkit\haxe\std/haxe/unit/TestRunner.hx line 115

* FileLengthCheckTest::testDefaultFileLength()
ERR: FileLengthCheckTest.hx:17(FileLengthCheckTest.testDefaultFileLength) - expe
cted 'Too many lines in file (> 2000)' but was ''

Called from C:\HaxeToolkit\haxe\std/haxe/unit/TestCase.hx line 69
Called from test/FileLengthCheckTest.hx line 17
Called from <builtin> line 1
Called from C:\HaxeToolkit\haxe\std/neko/_std/Reflect.hx line 58
Called from C:\HaxeToolkit\haxe\std/haxe/unit/TestRunner.hx line 115


FAILED 160 tests, 2 failed, 158 success
```

**Comment by Gama11** [comment]
One issue with the current reporter is that only the column is reported, not the actual character range.

**Comment by adireddy** [comment]
Used `\n` character to test file length, may be that's being replaced in FlashDevelop but not sure. Replaced those tests with simpler versions so it should work now.

When I get a chance I will look into reporting character range if haxeparser supports it.

**Comment by Gama11** [comment]
Oh, I guess you're not on Windows? I am, so this might be Git's autocrlf feature. That would also explain why it works on Travis.

I already have ranges mostly working.

**Comment by AlexHaxe** [comment]
I guess it has to do with how git handles line breaks. On Windows git replaces `\n` with `\r\n`, which will make `Checker.findLineSeparator` find `\r` as line separator for those checks. And since the tests add lots of `\n` they fail on Windows.
