### ISSUE TITLE
WhitespaceAround fails on comment after switch

### ISSUE THREAD

**Issue by Gama11** [adireddy/haxe-checkstyle#77]
``` haxe
class Test
{
    function foo()
    {
        switch ("Test") // broken
        {
        }
    }
}
```

```
./source/Test.hx:1: character 0 : Error: Check WhitespaceAfter failed: bad token CommentLine( broken) != BrOpen
```

**Comment by AlexHaxe** [comment]
I have added some support for comments, but I probably have missed a few places

**Comment by Gama11** [comment]
If this particular example now works, it's probably best to close and open a new issue for new cases?

Also, this should probably be added as a test?

**Comment by AlexHaxe** [comment]
yes, that's why I kept it open, I have to add a test case
